---
- hosts: all
  become: yes
  tasks:
    - name: create eth1 interface with IP address
      nmcli:
        name: eth-next
        type: ethernet
        state: present
        ip4: "192.168.1.10/24"